// <auto-generated />
using AvaloniaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AvaloniaApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926092841_NameOfUpdate")]
    partial class NameOfUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AvaloniaApp.Data.Equipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("equipment_pk");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("AvaloniaApp.Data.Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("Clientid")
                        .HasColumnType("bigint")
                        .HasColumnName("clientid");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("Mechaid")
                        .HasColumnType("bigint")
                        .HasColumnName("mechaid");

                    b.Property<int?>("SerialNumber")
                        .HasColumnType("integer")
                        .HasColumnName("serial_number");

                    b.Property<long?>("Type")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("request_pk");

                    b.HasIndex("Clientid");

                    b.HasIndex("Mechaid");

                    b.HasIndex("Type");

                    b.ToTable("request", (string)null);
                });

            modelBuilder.Entity("AvaloniaApp.Data.RequestEquipment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying")
                        .HasColumnName("id");

                    b.Property<long?>("Eqid")
                        .HasColumnType("bigint")
                        .HasColumnName("eqid");

                    b.Property<long?>("Reqid")
                        .HasColumnType("bigint")
                        .HasColumnName("reqid");

                    b.HasKey("Id")
                        .HasName("request_equipment_pk");

                    b.ToTable("request_equipment", (string)null);
                });

            modelBuilder.Entity("AvaloniaApp.Data.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("role_pk");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("AvaloniaApp.Data.TypeRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("type_request_pk");

                    b.ToTable("type_request", (string)null);
                });

            modelBuilder.Entity("AvaloniaApp.Data.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Passowrd")
                        .HasColumnType("text")
                        .HasColumnName("passowrd");

                    b.Property<long?>("Roleid")
                        .HasColumnType("bigint")
                        .HasColumnName("roleid");

                    b.HasKey("Id")
                        .HasName("user_pk");

                    b.HasIndex("Roleid");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AvaloniaApp.Data.Request", b =>
                {
                    b.HasOne("AvaloniaApp.Data.User", "Client")
                        .WithMany("RequestClients")
                        .HasForeignKey("Clientid")
                        .HasConstraintName("request_user_fk");

                    b.HasOne("AvaloniaApp.Data.User", "Mecha")
                        .WithMany("RequestMechas")
                        .HasForeignKey("Mechaid")
                        .HasConstraintName("request_user_fk_1");

                    b.HasOne("AvaloniaApp.Data.TypeRequest", "TypeNavigation")
                        .WithMany("Requests")
                        .HasForeignKey("Type")
                        .HasConstraintName("request_type_request_fk");

                    b.Navigation("Client");

                    b.Navigation("Mecha");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("AvaloniaApp.Data.User", b =>
                {
                    b.HasOne("AvaloniaApp.Data.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("Roleid")
                        .HasConstraintName("user_role_fk");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AvaloniaApp.Data.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AvaloniaApp.Data.TypeRequest", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("AvaloniaApp.Data.User", b =>
                {
                    b.Navigation("RequestClients");

                    b.Navigation("RequestMechas");
                });
#pragma warning restore 612, 618
        }
    }
}
